"""Generate Group11_Assignment2_report_v9.tex"""

lines = []

def w(*args):
    for a in args:
        lines.append(a)

w(
r'\documentclass[11pt,a4paper]{article}',
r'\usepackage[margin=2.4cm]{geometry}',
r'\usepackage{graphicx}',
r'\usepackage{caption}',
r'\usepackage{subcaption}',
r'\usepackage{float}',
r'\usepackage{booktabs}',
r'\usepackage{amsmath,amssymb}',
r'\usepackage{xcolor}',
r'\usepackage{multirow}',
r'\usepackage{array}',
r'\usepackage[colorlinks=true,linkcolor=blue!60!black,citecolor=blue!60!black,urlcolor=blue!60!black]{hyperref}',
r'',
r'\title{\textbf{Assignment 2: Fully Connected Neural Networks (FCNN)}\\[1em]',
r'\large Classification and Regression from Scratch Using SGD\\[2em]',
r'\normalsize\textbf{Group 11} --- CS601T Deep Learning\\[1.5em]',
r'\normalsize',
r'CS24BT055\enspace Himanshu Nagwanshi\\',
r'CS24BT061\enspace Sidharth B\\',
r'CS24BT060\enspace Anshuman Rahul}',
r'\author{}',
r'\date{}',
r'',
r'\begin{document}',
r'\maketitle',
r'\thispagestyle{empty}',
r'',
r'\begin{abstract}',
r'This report presents the design, implementation, and empirical evaluation of Fully Connected Neural Networks (FCNNs) built from scratch using NumPy, trained with Stochastic Gradient Descent (SGD) and squared error loss. In strict accordance with the assignment rubric, we report: (1) class-wise precision, recall, F-measure, mean metrics, accuracy, and confusion matrices for every evaluated architecture on the validation set, and for the best architecture on the test set; (2) RMSE and \%RMSE on training and validation data for all architectures, and on test data for the best architecture; (3) split-wise (train/val/test) decision regions, model-fit plots, scatter plots, and activation surfaces for every hidden and output node of the best architecture; (4) comparison with the single-neuron perceptron from Assignment~1. On the LS dataset, 1HL$\times$2 achieves 100\% test accuracy. On the NLS dataset, 2HL $16\times8$ achieves 100\% test accuracy. Regression achieves test \%RMSE of 3.20\% (univariate) and 1.42\% (bivariate 1HL), demonstrating the FCNN\'s superiority over any linear model.',
r'\end{abstract}',
r'',
r'\tableofcontents',
r'\newpage',
r'',
r'%===========================================================================',
r'\section{Model Architecture and Training Methodology}',
r'',
r'\subsection{Fully Connected Neural Network (FCNN)}',
r'Our FCNN supports arbitrary multi-layer feedforward topologies. Forward propagation through layer $l$:',
r'\begin{equation}',
r'\mathbf{z}^{(l)} = \mathbf{a}^{(l-1)}\mathbf{W}^{(l)} + \mathbf{b}^{(l)}, \quad \mathbf{a}^{(l)} = \phi^{(l)}(\mathbf{z}^{(l)})',
r'\end{equation}',
r'For \textbf{classification}: hidden layers use sigmoid $\sigma(z)=1/(1+e^{-z})$; the output layer uses \textbf{softmax} producing a normalised probability distribution over 3 classes. For \textbf{regression}: hidden layers use sigmoid; the output uses a \textbf{linear} (identity) activation. Weights initialised as $\mathcal{N}(0,\,1/\sqrt{n_{\text{in}}})$.',
r'',
r'\subsection{SGD and Backpropagation}',
r'Online SGD updates parameters after each individual training sample. Instantaneous squared error:',
r'\begin{equation}',
r'\mathcal{L} = \frac{1}{K}\sum_{k=1}^{K}(\hat{y}_k - y_k)^2',
r'\end{equation}',
r'For the softmax output the error signal uses the Jacobian identity. For sigmoid hidden units: $\delta^{(l)}_j = \left(\sum_k \delta^{(l+1)}_k w^{(l+1)}_{kj}\right) a^{(l)}_j (1 - a^{(l)}_j)$.',
r'',
r'\subsection{Training Configuration}',
r'\begin{table}[H]',
r'\centering',
r'\caption{Training hyperparameters.}',
r'\begin{tabular}{lll}',
r'\toprule',
r'Hyperparameter & Classification & Regression \\',
r'\midrule',
r'Output activation & Softmax & Linear \\',
r'Hidden activation & Sigmoid & Sigmoid \\',
r'Learning rate $\eta$ & 0.5 & 0.5 \\',
r'Max epochs & 800 & 800 \\',
r'Seed & 42 & 42 \\',
r'Weight init & $\mathcal{N}(0,1/\sqrt{n_{\text{in}}})$ & $\mathcal{N}(0,1/\sqrt{n_{\text{in}}})$ \\',
r'Train/Val/Test & 60/20/20 (stratified) & 60/20/20 \\',
r'\bottomrule',
r'\end{tabular}',
r'\end{table}',
r'',
r'%===========================================================================',
r'\section{Classification Tasks}',
r'',
r'\subsection{Dataset 1: Linearly Separable (LS) --- 1 Hidden Layer}',
r'',
r'The LS dataset contains 1,500 two-dimensional samples equally distributed across 3 classes (500 each). A 1HL architecture is evaluated. Hidden sizes swept: $h \in \{2,4,8,16,32\}$. Train/Val/Test: 900/300/300 (stratified, 100 per class per split).',
r'',
r'\subsubsection*{Validation Metrics Across All Architectures}',
r'',
r'\begin{table}[H]',
r'\centering',
r'\caption{Dataset 1 (LS): validation metrics for all 1HL architectures.}',
r'\small',
r'\begin{tabular}{lrrrrr}',
r'\toprule',
r'Metric & $h=2$ & $h=4$ & $h=8$ & $h=16$ & $h=32$ \\',
r'\midrule',
r'Accuracy        & 1.0000 & 1.0000 & 1.0000 & 1.0000 & 1.0000 \\',
r'Precision -- C0 & 1.0000 & 1.0000 & 1.0000 & 1.0000 & 1.0000 \\',
r'Precision -- C1 & 1.0000 & 1.0000 & 1.0000 & 1.0000 & 1.0000 \\',
r'Precision -- C2 & 1.0000 & 1.0000 & 1.0000 & 1.0000 & 1.0000 \\',
r'Mean Precision  & 1.0000 & 1.0000 & 1.0000 & 1.0000 & 1.0000 \\',
r'Recall -- C0    & 1.0000 & 1.0000 & 1.0000 & 1.0000 & 1.0000 \\',
r'Recall -- C1    & 1.0000 & 1.0000 & 1.0000 & 1.0000 & 1.0000 \\',
r'Recall -- C2    & 1.0000 & 1.0000 & 1.0000 & 1.0000 & 1.0000 \\',
r'Mean Recall     & 1.0000 & 1.0000 & 1.0000 & 1.0000 & 1.0000 \\',
r'F-measure -- C0 & 1.0000 & 1.0000 & 1.0000 & 1.0000 & 1.0000 \\',
r'F-measure -- C1 & 1.0000 & 1.0000 & 1.0000 & 1.0000 & 1.0000 \\',
r'F-measure -- C2 & 1.0000 & 1.0000 & 1.0000 & 1.0000 & 1.0000 \\',
r'Mean F-measure  & 1.0000 & 1.0000 & 1.0000 & 1.0000 & 1.0000 \\',
r'\bottomrule',
r'\end{tabular}',
r'\end{table}',
r'',
r'\begin{table}[H]',
r'\centering',
r'\caption{Dataset 1 (LS): validation confusion matrix (identical across all architectures).}',
r'\begin{tabular}{lrrr}',
r'\toprule',
r'True Class & Pred.\ 0 & Pred.\ 1 & Pred.\ 2 \\',
r'\midrule',
r'Class 0 & 100 & 0 & 0 \\',
r'Class 1 & 0   & 100 & 0 \\',
r'Class 2 & 0   & 0 & 100 \\',
r'\bottomrule',
r'\end{tabular}',
r'\end{table}',
r'',
r'All five architectures achieve perfect validation accuracy. The smallest ($h=2$) is selected as the best (fewest parameters). \textbf{Best: 1HL$\times$2}.',
r'',
r'\subsubsection*{Test Results for Best Architecture (1HL$\times$2)}',
r'',
r'\begin{table}[H]',
r'\centering',
r'\caption{Dataset 1 (LS): test metrics --- best architecture (1HL$\times$2).}',
r'\begin{tabular}{lr}',
r'\toprule',
r'Metric & Value \\',
r'\midrule',
r'Accuracy        & 1.0000 \\',
r'Precision -- C0 & 1.0000 \\',
r'Precision -- C1 & 1.0000 \\',
r'Precision -- C2 & 1.0000 \\',
r'Mean Precision  & 1.0000 \\',
r'Recall -- C0    & 1.0000 \\',
r'Recall -- C1    & 1.0000 \\',
r'Recall -- C2    & 1.0000 \\',
r'Mean Recall     & 1.0000 \\',
r'F-measure -- C0 & 1.0000 \\',
r'F-measure -- C1 & 1.0000 \\',
r'F-measure -- C2 & 1.0000 \\',
r'Mean F-measure  & 1.0000 \\',
r'\bottomrule',
r'\end{tabular}',
r'\end{table}',
r'',
r'\begin{table}[H]',
r'\centering',
r'\caption{Dataset 1 (LS): test confusion matrix --- best architecture (1HL$\times$2).}',
r'\begin{tabular}{lrrr}',
r'\toprule',
r'True Class & Pred.\ 0 & Pred.\ 1 & Pred.\ 2 \\',
r'\midrule',
r'Class 0 & 100 & 0   & 0   \\',
r'Class 1 & 0   & 100 & 0   \\',
r'Class 2 & 0   & 0   & 100 \\',
r'\bottomrule',
r'\end{tabular}',
r'\end{table}',
r'',
r'\subsubsection*{Error Convergence}',
r'',
r'\begin{figure}[H]',
r'    \centering',
r'    \includegraphics[width=0.65\linewidth]{outputs/classification/ls/h2/error_curve.png}',
r'    \caption{Dataset 1 (LS): error vs.\ epoch --- best architecture (1HL$\times$2).}',
r'\end{figure}',
r'',
r'\subsubsection*{Decision Regions}',
r'',
r'\begin{figure}[H]',
r'    \centering',
r'    \begin{subfigure}[b]{0.32\textwidth}',
r'        \includegraphics[width=\textwidth]{outputs/classification/ls/best/decision_regions_train.png}',
r'        \caption{Training}',
r'    \end{subfigure}',
r'    \begin{subfigure}[b]{0.32\textwidth}',
r'        \includegraphics[width=\textwidth]{outputs/classification/ls/best/decision_regions_val.png}',
r'        \caption{Validation}',
r'    \end{subfigure}',
r'    \begin{subfigure}[b]{0.32\textwidth}',
r'        \includegraphics[width=\textwidth]{outputs/classification/ls/best/decision_regions_test.png}',
r'        \caption{Test}',
r'    \end{subfigure}',
r'    \caption{Dataset 1 (LS): decision regions --- best architecture (1HL$\times$2) across train/val/test.}',
r'\end{figure}',
r'',
r'\begin{figure}[H]',
r'    \centering',
r'    \includegraphics[width=0.5\linewidth]{outputs/classification/ls/best/cm_test.png}',
r'    \caption{Dataset 1 (LS): test confusion matrix heatmap --- 1HL$\times$2.}',
r'\end{figure}',
r'',
r'\subsubsection*{Node Output Surfaces --- All Nodes, Best Architecture (1HL$\times$2)}',
r'',
r'\begin{figure}[H]',
r'    \centering',
r'    \begin{subfigure}[b]{0.32\textwidth}',
r'        \includegraphics[width=\textwidth]{outputs/classification/ls/best/train/surface_hidden_l1_n0.png}',
r'        \caption{H1-N0 (Train)}',
r'    \end{subfigure}',
r'    \begin{subfigure}[b]{0.32\textwidth}',
r'        \includegraphics[width=\textwidth]{outputs/classification/ls/best/val/surface_hidden_l1_n0.png}',
r'        \caption{H1-N0 (Val)}',
r'    \end{subfigure}',
r'    \begin{subfigure}[b]{0.32\textwidth}',
r'        \includegraphics[width=\textwidth]{outputs/classification/ls/best/test/surface_hidden_l1_n0.png}',
r'        \caption{H1-N0 (Test)}',
r'    \end{subfigure}',
r'    \vspace{0.3cm}',
r'    \begin{subfigure}[b]{0.32\textwidth}',
r'        \includegraphics[width=\textwidth]{outputs/classification/ls/best/train/surface_hidden_l1_n1.png}',
r'        \caption{H1-N1 (Train)}',
r'    \end{subfigure}',
r'    \begin{subfigure}[b]{0.32\textwidth}',
r'        \includegraphics[width=\textwidth]{outputs/classification/ls/best/val/surface_hidden_l1_n1.png}',
r'        \caption{H1-N1 (Val)}',
r'    \end{subfigure}',
r'    \begin{subfigure}[b]{0.32\textwidth}',
r'        \includegraphics[width=\textwidth]{outputs/classification/ls/best/test/surface_hidden_l1_n1.png}',
r'        \caption{H1-N1 (Test)}',
r'    \end{subfigure}',
r'    \vspace{0.3cm}',
r'    \begin{subfigure}[b]{0.32\textwidth}',
r'        \includegraphics[width=\textwidth]{outputs/classification/ls/best/train/surface_output_l2_n0.png}',
r'        \caption{Out-N0 (Train)}',
r'    \end{subfigure}',
r'    \begin{subfigure}[b]{0.32\textwidth}',
r'        \includegraphics[width=\textwidth]{outputs/classification/ls/best/val/surface_output_l2_n0.png}',
r'        \caption{Out-N0 (Val)}',
r'    \end{subfigure}',
r'    \begin{subfigure}[b]{0.32\textwidth}',
r'        \includegraphics[width=\textwidth]{outputs/classification/ls/best/test/surface_output_l2_n0.png}',
r'        \caption{Out-N0 (Test)}',
r'    \end{subfigure}',
r'    \vspace{0.3cm}',
r'    \begin{subfigure}[b]{0.32\textwidth}',
r'        \includegraphics[width=\textwidth]{outputs/classification/ls/best/train/surface_output_l2_n1.png}',
r'        \caption{Out-N1 (Train)}',
r'    \end{subfigure}',
r'    \begin{subfigure}[b]{0.32\textwidth}',
r'        \includegraphics[width=\textwidth]{outputs/classification/ls/best/val/surface_output_l2_n1.png}',
r'        \caption{Out-N1 (Val)}',
r'    \end{subfigure}',
r'    \begin{subfigure}[b]{0.32\textwidth}',
r'        \includegraphics[width=\textwidth]{outputs/classification/ls/best/test/surface_output_l2_n1.png}',
r'        \caption{Out-N1 (Test)}',
r'    \end{subfigure}',
r'    \vspace{0.3cm}',
r'    \begin{subfigure}[b]{0.32\textwidth}',
r'        \includegraphics[width=\textwidth]{outputs/classification/ls/best/train/surface_output_l2_n2.png}',
r'        \caption{Out-N2 (Train)}',
r'    \end{subfigure}',
r'    \begin{subfigure}[b]{0.32\textwidth}',
r'        \includegraphics[width=\textwidth]{outputs/classification/ls/best/val/surface_output_l2_n2.png}',
r'        \caption{Out-N2 (Val)}',
r'    \end{subfigure}',
r'    \begin{subfigure}[b]{0.32\textwidth}',
r'        \includegraphics[width=\textwidth]{outputs/classification/ls/best/test/surface_output_l2_n2.png}',
r'        \caption{Out-N2 (Test)}',
r'    \end{subfigure}',
r'    \caption{Dataset 1 (LS): 3D activation surfaces for \textbf{all} nodes of the best 1HL$\times$2 architecture. Rows: H1-N0, H1-N1 (both hidden nodes); Out-N0, Out-N1, Out-N2 (all 3 output nodes). Columns: Training, Validation, Test.}',
r'\end{figure}',
r'',
r'\subsubsection*{Analysis and Inferences}',
r'\begin{itemize}',
r'    \item All five architectures achieve 100\% validation and test accuracy, consistent with the large geometric separation of the three Gaussian clusters. Even the minimal 2-node hidden layer suffices.',
r'    \item The error curve drops steeply and reaches near-zero within the first 50 epochs.',
r'    \item Hidden node surfaces show smooth sigmoid hyperplane projections. Softmax output nodes form clear high-activation regions ($\approx 1$) over each target class.',
r'    \item Decision regions and node surfaces are consistent across train/val/test, confirming perfect generalisation.',
r'\end{itemize}',
r'',
r'%===========================================================================',
r'\subsection{Dataset 2: Non-Linearly Separable (NLS) --- 2 Hidden Layers}',
r'',
r'The NLS dataset contains 1,700 two-dimensional samples across 3 classes (500/500/700). A 2HL bottleneck architecture is evaluated: first layer $h$, second layer $h/2$; $h \in \{2,4,8,16,32\}$ giving $(2\times1),(4\times2),(8\times4),(16\times8),(32\times16)$. Train/Val/Test: 1020/340/340 (stratified). The data exhibits concentric ring structure requiring non-linear boundaries.',
r'',
r'\subsubsection*{Validation Metrics Across All Architectures}',
r'',
r'\begin{table}[H]',
r'\centering',
r'\caption{Dataset 2 (NLS): validation metrics for all 2HL architectures.}',
r'\small',
r'\begin{tabular}{lrrrrr}',
r'\toprule',
r'Metric & $2\times1$ & $4\times2$ & $8\times4$ & $16\times8$ & $32\times16$ \\',
r'\midrule',
r'Accuracy        & 0.6559 & 0.8971 & 0.9971 & \textbf{1.0000} & 1.0000 \\',
r'Precision -- C0 & 0.7007 & 0.9429 & 1.0000 & 1.0000 & 1.0000 \\',
r'Precision -- C1 & 0.0000 & 0.9851 & 1.0000 & 1.0000 & 1.0000 \\',
r'Precision -- C2 & 0.6256 & 0.8333 & 0.9929 & 1.0000 & 1.0000 \\',
r'Mean Precision  & 0.4421 & 0.9204 & 0.9976 & 1.0000 & 1.0000 \\',
r'Recall -- C0    & 0.9600 & 0.9900 & 1.0000 & 1.0000 & 1.0000 \\',
r'Recall -- C1    & 0.0000 & 0.6600 & 0.9900 & 1.0000 & 1.0000 \\',
r'Recall -- C2    & 0.9071 & 1.0000 & 1.0000 & 1.0000 & 1.0000 \\',
r'Mean Recall     & 0.6224 & 0.8833 & 0.9967 & 1.0000 & 1.0000 \\',
r'F-measure -- C0 & 0.8101 & 0.9659 & 1.0000 & 1.0000 & 1.0000 \\',
r'F-measure -- C1 & 0.0000 & 0.7904 & 0.9950 & 1.0000 & 1.0000 \\',
r'F-measure -- C2 & 0.7405 & 0.9091 & 0.9964 & 1.0000 & 1.0000 \\',
r'Mean F-measure  & 0.5169 & 0.8885 & 0.9971 & 1.0000 & 1.0000 \\',
r'\bottomrule',
r'\end{tabular}',
r'\end{table}',
r'',
r'\begin{table}[H]',
r'\centering',
r'\caption{Dataset 2 (NLS): validation confusion matrices for all architectures.}',
r'\small',
r'\begin{tabular}{llrrr}',
r'\toprule',
r'Architecture & True Class & Pred.\ 0 & Pred.\ 1 & Pred.\ 2 \\',
r'\midrule',
r'\multirow{3}{*}{$2\times1$}   & Class 0 & 96  & 0   & 4   \\',
r'                               & Class 1 & 28  & 0   & 72  \\',
r'                               & Class 2 & 13  & 0   & 127 \\',
r'\midrule',
r'\multirow{3}{*}{$4\times2$}   & Class 0 & 99  & 1   & 0   \\',
r'                               & Class 1 & 6   & 66  & 28  \\',
r'                               & Class 2 & 0   & 0   & 140 \\',
r'\midrule',
r'\multirow{3}{*}{$8\times4$}   & Class 0 & 100 & 0   & 0   \\',
r'                               & Class 1 & 0   & 99  & 1   \\',
r'                               & Class 2 & 0   & 0   & 140 \\',
r'\midrule',
r'\multirow{3}{*}{$16\times8$}  & Class 0 & 100 & 0   & 0   \\',
r'                               & Class 1 & 0   & 100 & 0   \\',
r'                               & Class 2 & 0   & 0   & 140 \\',
r'\midrule',
r'\multirow{3}{*}{$32\times16$} & Class 0 & 100 & 0   & 0   \\',
r'                               & Class 1 & 0   & 100 & 0   \\',
r'                               & Class 2 & 0   & 0   & 140 \\',
r'\bottomrule',
r'\end{tabular}',
r'\end{table}',
r'',
r'The $16\times8$ architecture achieves perfect validation accuracy (100\%) with fewer parameters than $32\times16$. \textbf{Best: 2HL $16\times8$}.',
r'',
r'\subsubsection*{Test Results for Best Architecture (2HL $16\times8$)}',
r'',
r'\begin{table}[H]',
r'\centering',
r'\caption{Dataset 2 (NLS): test metrics --- best architecture (2HL $16\times8$).}',
r'\begin{tabular}{lr}',
r'\toprule',
r'Metric & Value \\',
r'\midrule',
r'Accuracy        & 1.0000 \\',
r'Precision -- C0 & 1.0000 \\',
r'Precision -- C1 & 1.0000 \\',
r'Precision -- C2 & 1.0000 \\',
r'Mean Precision  & 1.0000 \\',
r'Recall -- C0    & 1.0000 \\',
r'Recall -- C1    & 1.0000 \\',
r'Recall -- C2    & 1.0000 \\',
r'Mean Recall     & 1.0000 \\',
r'F-measure -- C0 & 1.0000 \\',
r'F-measure -- C1 & 1.0000 \\',
r'F-measure -- C2 & 1.0000 \\',
r'Mean F-measure  & 1.0000 \\',
r'\bottomrule',
r'\end{tabular}',
r'\end{table}',
r'',
r'\begin{table}[H]',
r'\centering',
r'\caption{Dataset 2 (NLS): test confusion matrix --- best architecture (2HL $16\times8$). All 340 test samples correctly classified.}',
r'\begin{tabular}{lrrr}',
r'\toprule',
r'True Class & Pred.\ 0 & Pred.\ 1 & Pred.\ 2 \\',
r'\midrule',
r'Class 0 & 100 & 0   & 0   \\',
r'Class 1 & 0   & 100 & 0   \\',
r'Class 2 & 0   & 0   & 140 \\',
r'\bottomrule',
r'\end{tabular}',
r'\end{table}',
r'',
r'\subsubsection*{Error Convergence}',
r'',
r'\begin{figure}[H]',
r'    \centering',
r'    \includegraphics[width=0.65\linewidth]{outputs/classification/nls/h16/error_curve.png}',
r'    \caption{Dataset 2 (NLS): error vs.\ epoch --- best architecture (2HL $16\times8$).}',
r'\end{figure}',
r'',
r'\subsubsection*{Decision Regions}',
r'',
r'\begin{figure}[H]',
r'    \centering',
r'    \begin{subfigure}[b]{0.32\textwidth}',
r'        \includegraphics[width=\textwidth]{outputs/classification/nls/best/decision_regions_train.png}',
r'        \caption{Training}',
r'    \end{subfigure}',
r'    \begin{subfigure}[b]{0.32\textwidth}',
r'        \includegraphics[width=\textwidth]{outputs/classification/nls/best/decision_regions_val.png}',
r'        \caption{Validation}',
r'    \end{subfigure}',
r'    \begin{subfigure}[b]{0.32\textwidth}',
r'        \includegraphics[width=\textwidth]{outputs/classification/nls/best/decision_regions_test.png}',
r'        \caption{Test}',
r'    \end{subfigure}',
r'    \caption{Dataset 2 (NLS): decision regions --- 2HL $16\times8$. The network learns concentric non-linear boundaries separating all three ring-structured classes.}',
r'\end{figure}',
r'',
r'\begin{figure}[H]',
r'    \centering',
r'    \includegraphics[width=0.5\linewidth]{outputs/classification/nls/best/cm_test.png}',
r'    \caption{Dataset 2 (NLS): test confusion matrix heatmap --- best architecture (2HL $16\times8$).}',
r'\end{figure}',
r'',
r'\subsubsection*{Node Output Surfaces --- Best Architecture (2HL $16\times8$)}',
r'',
r'The $16\times8$ architecture has 16 first-layer nodes, 8 second-layer nodes, and 3 output nodes. H1-N0, H2-N0, and all 3 output nodes are shown below; additional hidden node surfaces are in Appendix~\ref{app:nls}.',
r'',
r'\begin{figure}[H]',
r'    \centering',
r'    \begin{subfigure}[b]{0.32\textwidth}',
r'        \includegraphics[width=\textwidth]{outputs/classification/nls/best/train/surface_hidden_l1_n0.png}',
r'        \caption{H1-N0 (Train)}',
r'    \end{subfigure}',
r'    \begin{subfigure}[b]{0.32\textwidth}',
r'        \includegraphics[width=\textwidth]{outputs/classification/nls/best/val/surface_hidden_l1_n0.png}',
r'        \caption{H1-N0 (Val)}',
r'    \end{subfigure}',
r'    \begin{subfigure}[b]{0.32\textwidth}',
r'        \includegraphics[width=\textwidth]{outputs/classification/nls/best/test/surface_hidden_l1_n0.png}',
r'        \caption{H1-N0 (Test)}',
r'    \end{subfigure}',
r'    \vspace{0.3cm}',
r'    \begin{subfigure}[b]{0.32\textwidth}',
r'        \includegraphics[width=\textwidth]{outputs/classification/nls/best/train/surface_hidden_l2_n0.png}',
r'        \caption{H2-N0 (Train)}',
r'    \end{subfigure}',
r'    \begin{subfigure}[b]{0.32\textwidth}',
r'        \includegraphics[width=\textwidth]{outputs/classification/nls/best/val/surface_hidden_l2_n0.png}',
r'        \caption{H2-N0 (Val)}',
r'    \end{subfigure}',
r'    \begin{subfigure}[b]{0.32\textwidth}',
r'        \includegraphics[width=\textwidth]{outputs/classification/nls/best/test/surface_hidden_l2_n0.png}',
r'        \caption{H2-N0 (Test)}',
r'    \end{subfigure}',
r'    \vspace{0.3cm}',
r'    \begin{subfigure}[b]{0.32\textwidth}',
r'        \includegraphics[width=\textwidth]{outputs/classification/nls/best/train/surface_output_l3_n0.png}',
r'        \caption{Out-N0 (Train)}',
r'    \end{subfigure}',
r'    \begin{subfigure}[b]{0.32\textwidth}',
r'        \includegraphics[width=\textwidth]{outputs/classification/nls/best/val/surface_output_l3_n0.png}',
r'        \caption{Out-N0 (Val)}',
r'    \end{subfigure}',
r'    \begin{subfigure}[b]{0.32\textwidth}',
r'        \includegraphics[width=\textwidth]{outputs/classification/nls/best/test/surface_output_l3_n0.png}',
r'        \caption{Out-N0 (Test)}',
r'    \end{subfigure}',
r'    \vspace{0.3cm}',
r'    \begin{subfigure}[b]{0.32\textwidth}',
r'        \includegraphics[width=\textwidth]{outputs/classification/nls/best/train/surface_output_l3_n1.png}',
r'        \caption{Out-N1 (Train)}',
r'    \end{subfigure}',
r'    \begin{subfigure}[b]{0.32\textwidth}',
r'        \includegraphics[width=\textwidth]{outputs/classification/nls/best/val/surface_output_l3_n1.png}',
r'        \caption{Out-N1 (Val)}',
r'    \end{subfigure}',
r'    \begin{subfigure}[b]{0.32\textwidth}',
r'        \includegraphics[width=\textwidth]{outputs/classification/nls/best/test/surface_output_l3_n1.png}',
r'        \caption{Out-N1 (Test)}',
r'    \end{subfigure}',
r'    \vspace{0.3cm}',
r'    \begin{subfigure}[b]{0.32\textwidth}',
r'        \includegraphics[width=\textwidth]{outputs/classification/nls/best/train/surface_output_l3_n2.png}',
r'        \caption{Out-N2 (Train)}',
r'    \end{subfigure}',
r'    \begin{subfigure}[b]{0.32\textwidth}',
r'        \includegraphics[width=\textwidth]{outputs/classification/nls/best/val/surface_output_l3_n2.png}',
r'        \caption{Out-N2 (Val)}',
r'    \end{subfigure}',
r'    \begin{subfigure}[b]{0.32\textwidth}',
r'        \includegraphics[width=\textwidth]{outputs/classification/nls/best/test/surface_output_l3_n2.png}',
r'        \caption{Out-N2 (Test)}',
r'    \end{subfigure}',
r'    \caption{Dataset 2 (NLS) --- 2HL $16\times8$: H1-N0, H2-N0, Out-N0, Out-N1, Out-N2 across train/val/test. Additional hidden node surfaces are in Appendix~\ref{app:nls}.}',
r'\end{figure}',
r'',
r'\subsubsection*{Analysis and Inferences}',
r'\begin{itemize}',
r'    \item $2\times1$ achieves only 65.6\% validation accuracy; insufficient units cannot construct curved annular boundaries.',
r'    \item $4\times2$ (89.7\%) partially separates classes but fails on Class~1 (middle ring).',
r'    \item $8\times4$ achieves 99.7\% with 1 error; $16\times8$ achieves 100\% on both validation and test.',
r'    \item The 2HL bottleneck ($h_1>h_2$) forces compressed representations in the second hidden layer, acting as a learned feature extractor over the non-linear basis from the first layer.',
r'    \item All output softmax surfaces show near-binary activation fields: the correct class region approaches 1.0 and the rest approach 0.0.',
r'\end{itemize}',
r'',
r'\subsection{Comparison with Assignment 1: Classification}',
r'',
r'\begin{table}[H]',
r'\centering',
r'\caption{Classification: Assignment~1 (single-neuron OvO perceptron) vs.\ Assignment~2 (FCNN).}',
r'\begin{tabular}{lllr}',
r'\toprule',
r'Dataset & Model & Approach & Test Accuracy \\',
r'\midrule',
r'Dataset 1 (LS)  & Single Neuron (A1) & OvO, 3 binary perceptrons & 1.0000 \\',
r'                & FCNN (A2, 1HL$\times$2) & Unified 3-output softmax network & 1.0000 \\',
r'\midrule',
r'Dataset 2 (NLS) & Single Neuron (A1) & OvO (linear boundaries) & 0.2660 \\',
r'                & FCNN (A2, 2HL $16\times8$) & Two hidden layers, sigmoid+softmax & 1.0000 \\',
r'\bottomrule',
r'\end{tabular}',
r'\end{table}',
r'',
r'On the NLS dataset the single-neuron model achieves only 26.6\% (below random chance), as a linear boundary cannot isolate any concentric ring. The FCNN achieves 100\% by composing sigmoid activations to construct circular decision boundaries.',
r'',
r'%===========================================================================',
r'\section{Regression Tasks}',
r'',
r'\subsection{Evaluation Metrics}',
r'',
r'\begin{equation}',
r'\text{RMSE} = \sqrt{\frac{1}{N}\sum_{i=1}^{N}(y_i - \hat{y}_i)^2}, \qquad \%\text{RMSE} = \frac{\text{RMSE}}{y_{\max} - y_{\min}} \times 100',
r'\end{equation}',
r'',
r'\subsection{Dataset 1: Univariate Regression ($d=1$)}',
r'',
r'Dataset: 1,000 samples, single input $x$, continuous target $y$. 1HL architecture; $h \in \{2,4,8,16,32\}$. Train/Val/Test: 600/200/200.',
r'',
r'\subsubsection*{RMSE and \%RMSE for All Architectures}',
r'',
r'\begin{table}[H]',
r'\centering',
r'\caption{Univariate regression: RMSE and \%RMSE on training and validation data. Bold = best (selected) architecture.}',
r'\begin{tabular}{lrrrr}',
r'\toprule',
r'Architecture & Train RMSE & Train \%RMSE & Val RMSE & Val \%RMSE \\',
r'\midrule',
r'\textbf{1HL$\times$2}  & \textbf{0.0760} & \textbf{2.960\%} & \textbf{0.0699} & \textbf{2.814\%} \\',
r'1HL$\times$4  & 0.0998 & 3.884\% & 0.0928 & 3.734\% \\',
r'1HL$\times$8  & 0.0938 & 3.653\% & 0.0882 & 3.550\% \\',
r'1HL$\times$16 & 0.1437 & 5.592\% & 0.1401 & 5.638\% \\',
r'1HL$\times$32 & 0.1179 & 4.589\% & 0.1121 & 4.510\% \\',
r'\bottomrule',
r'\end{tabular}',
r'\end{table}',
r'',
r'\begin{table}[H]',
r'\centering',
r'\caption{Univariate regression: RMSE and \%RMSE on test data --- best architecture (1HL$\times$2).}',
r'\begin{tabular}{lrr}',
r'\toprule',
r'Split & RMSE & \%RMSE \\',
r'\midrule',
r'Train      & 0.0760 & 2.960\% \\',
r'Validation & 0.0699 & 2.814\% \\',
r'Test       & 0.0738 & 3.198\% \\',
r'\bottomrule',
r'\end{tabular}',
r'\end{table}',
r'',
r'\subsubsection*{Error Convergence}',
r'',
r'\begin{figure}[H]',
r'    \centering',
r'    \includegraphics[width=0.65\linewidth]{outputs/regression/univariate/h2/error_curve.png}',
r'    \caption{Univariate regression: error vs.\ epoch --- best architecture (1HL$\times$2).}',
r'\end{figure}',
r'',
r'\subsubsection*{Model Output Superimposed on Target}',
r'',
r'\begin{figure}[H]',
r'    \centering',
r'    \begin{subfigure}[b]{0.32\textwidth}',
r'        \includegraphics[width=\textwidth]{outputs/regression/univariate/best/superimposed_train.png}',
r'        \caption{Training}',
r'    \end{subfigure}',
r'    \begin{subfigure}[b]{0.32\textwidth}',
r'        \includegraphics[width=\textwidth]{outputs/regression/univariate/best/superimposed_val.png}',
r'        \caption{Validation}',
r'    \end{subfigure}',
r'    \begin{subfigure}[b]{0.32\textwidth}',
r'        \includegraphics[width=\textwidth]{outputs/regression/univariate/best/superimposed_test.png}',
r'        \caption{Test}',
r'    \end{subfigure}',
r'    \caption{Univariate regression: model output superimposed on target --- 1HL$\times$2.}',
r'\end{figure}',
r'',
r'\subsubsection*{Scatter Plot: Target vs.\ Model Output}',
r'',
r'\begin{figure}[H]',
r'    \centering',
r'    \begin{subfigure}[b]{0.32\textwidth}',
r'        \includegraphics[width=\textwidth]{outputs/regression/univariate/best/scatter_train.png}',
r'        \caption{Training}',
r'    \end{subfigure}',
r'    \begin{subfigure}[b]{0.32\textwidth}',
r'        \includegraphics[width=\textwidth]{outputs/regression/univariate/best/scatter_val.png}',
r'        \caption{Validation}',
r'    \end{subfigure}',
r'    \begin{subfigure}[b]{0.32\textwidth}',
r'        \includegraphics[width=\textwidth]{outputs/regression/univariate/best/scatter_test.png}',
r'        \caption{Test}',
r'    \end{subfigure}',
r'    \caption{Univariate regression: scatter plots of target (x-axis) vs.\ model output (y-axis) --- 1HL$\times$2.}',
r'\end{figure}',
r'',
r'\subsubsection*{Node Output Curves --- All Nodes, Best Architecture (1HL$\times$2)}',
r'',
r'\begin{figure}[H]',
r'    \centering',
r'    \begin{subfigure}[b]{0.32\textwidth}',
r'        \includegraphics[width=\textwidth]{outputs/regression/univariate/best/train/curve_hidden_l1_n0.png}',
r'        \caption{H1-N0 (Train)}',
r'    \end{subfigure}',
r'    \begin{subfigure}[b]{0.32\textwidth}',
r'        \includegraphics[width=\textwidth]{outputs/regression/univariate/best/val/curve_hidden_l1_n0.png}',
r'        \caption{H1-N0 (Val)}',
r'    \end{subfigure}',
r'    \begin{subfigure}[b]{0.32\textwidth}',
r'        \includegraphics[width=\textwidth]{outputs/regression/univariate/best/test/curve_hidden_l1_n0.png}',
r'        \caption{H1-N0 (Test)}',
r'    \end{subfigure}',
r'    \vspace{0.3cm}',
r'    \begin{subfigure}[b]{0.32\textwidth}',
r'        \includegraphics[width=\textwidth]{outputs/regression/univariate/best/train/curve_hidden_l1_n1.png}',
r'        \caption{H1-N1 (Train)}',
r'    \end{subfigure}',
r'    \begin{subfigure}[b]{0.32\textwidth}',
r'        \includegraphics[width=\textwidth]{outputs/regression/univariate/best/val/curve_hidden_l1_n1.png}',
r'        \caption{H1-N1 (Val)}',
r'    \end{subfigure}',
r'    \begin{subfigure}[b]{0.32\textwidth}',
r'        \includegraphics[width=\textwidth]{outputs/regression/univariate/best/test/curve_hidden_l1_n1.png}',
r'        \caption{H1-N1 (Test)}',
r'    \end{subfigure}',
r'    \vspace{0.3cm}',
r'    \begin{subfigure}[b]{0.32\textwidth}',
r'        \includegraphics[width=\textwidth]{outputs/regression/univariate/best/train/curve_output_l2_n0.png}',
r'        \caption{Output Node (Train)}',
r'    \end{subfigure}',
r'    \begin{subfigure}[b]{0.32\textwidth}',
r'        \includegraphics[width=\textwidth]{outputs/regression/univariate/best/val/curve_output_l2_n0.png}',
r'        \caption{Output Node (Val)}',
r'    \end{subfigure}',
r'    \begin{subfigure}[b]{0.32\textwidth}',
r'        \includegraphics[width=\textwidth]{outputs/regression/univariate/best/test/curve_output_l2_n0.png}',
r'        \caption{Output Node (Test)}',
r'    \end{subfigure}',
r'    \caption{Univariate regression: node output curves for \textbf{all} nodes (H1-N0, H1-N1, output node) of the best 1HL$\times$2 architecture across train/val/test.}',
r'\end{figure}',
r'',
r'%===========================================================================',
r'\subsection{Dataset 2: Bivariate Regression ($d=2$)}',
r'',
r'Dataset: 10,201 samples on a 101$\times$101 grid, inputs $x_1,x_2$, continuous target $y$. Both \textbf{1HL and 2HL} architectures are evaluated as required by the rubric. $h \in \{2,4,8,16,32\}$; for 2HL the second layer is $h/2$. Train/Val/Test: 6120/2040/2041.',
r'',
r'\subsubsection*{RMSE and \%RMSE for All Architectures}',
r'',
r'\begin{table}[H]',
r'\centering',
r'\caption{Bivariate regression: RMSE and \%RMSE on training and validation data for all 1HL and 2HL architectures.}',
r'\small',
r'\begin{tabular}{llrrrr}',
r'\toprule',
r'Variant & Arch. & Train RMSE & Train \%RMSE & Val RMSE & Val \%RMSE \\',
r'\midrule',
r'\multirow{5}{*}{1HL}',
r' & $h=2$   & 0.0833 & 2.038\% & 0.0846 & 2.129\% \\',
r' & $h=4$   & 0.0791 & 1.934\% & 0.0816 & 2.053\% \\',
r' & $h=8$   & 0.0635 & 1.551\% & 0.0660 & 1.661\% \\',
r' & \textbf{$h=16$} & \textbf{0.0571} & \textbf{1.396\%} & \textbf{0.0576} & \textbf{1.448\%} \\',
r' & $h=32$  & 0.0591 & 1.446\% & 0.0592 & 1.489\% \\',
r'\midrule',
r'\multirow{5}{*}{2HL}',
r' & $2\times1$   & 0.3358 & 8.209\% & 0.3365 & 8.464\% \\',
r' & $4\times2$   & 0.0652 & 1.594\% & 0.0677 & 1.702\% \\',
r' & $8\times4$   & 0.0672 & 1.644\% & 0.0687 & 1.728\% \\',
r' & \textbf{$16\times8$} & \textbf{0.0586} & \textbf{1.433\%} & \textbf{0.0596} & \textbf{1.499\%} \\',
r' & $32\times16$ & 0.0688 & 1.682\% & 0.0662 & 1.664\% \\',
r'\bottomrule',
r'\end{tabular}',
r'\end{table}',
r'',
r'\begin{table}[H]',
r'\centering',
r'\caption{Bivariate regression: test RMSE and \%RMSE --- best architectures.}',
r'\begin{tabular}{llrr}',
r'\toprule',
r'Variant & Best Arch. & Test RMSE & Test \%RMSE \\',
r'\midrule',
r'1HL & $h=16$     & 0.0569 & 1.417\% \\',
r'2HL & $16\times8$ & 0.0585 & 1.457\% \\',
r'\bottomrule',
r'\end{tabular}',
r'\end{table}',
r'',
r'\subsubsection*{Error Convergence}',
r'',
r'\begin{figure}[H]',
r'    \centering',
r'    \begin{subfigure}[b]{0.48\textwidth}',
r'        \includegraphics[width=\textwidth]{outputs/regression/bivariate/1hl/h16/error_curve.png}',
r'        \caption{1HL$\times$16}',
r'    \end{subfigure}',
r'    \begin{subfigure}[b]{0.48\textwidth}',
r'        \includegraphics[width=\textwidth]{outputs/regression/bivariate/2hl/h16/error_curve.png}',
r'        \caption{2HL $16\times8$}',
r'    \end{subfigure}',
r'    \caption{Bivariate regression: error vs.\ epoch for best 1HL and 2HL architectures.}',
r'\end{figure}',
r'',
r'\subsubsection*{Model Output Superimposed on Target}',
r'',
r'\begin{figure}[H]',
r'    \centering',
r'    \begin{subfigure}[b]{0.32\textwidth}',
r'        \includegraphics[width=\textwidth]{outputs/regression/bivariate/2hl/best/superimposed_train.png}',
r'        \caption{Train (2HL)}',
r'    \end{subfigure}',
r'    \begin{subfigure}[b]{0.32\textwidth}',
r'        \includegraphics[width=\textwidth]{outputs/regression/bivariate/2hl/best/superimposed_val.png}',
r'        \caption{Val (2HL)}',
r'    \end{subfigure}',
r'    \begin{subfigure}[b]{0.32\textwidth}',
r'        \includegraphics[width=\textwidth]{outputs/regression/bivariate/2hl/best/superimposed_test.png}',
r'        \caption{Test (2HL)}',
r'    \end{subfigure}',
r'    \caption{Bivariate regression (2HL $16\times8$): 3D model output surface superimposed on target.}',
r'\end{figure}',
r'',
r'\begin{figure}[H]',
r'    \centering',
r'    \begin{subfigure}[b]{0.32\textwidth}',
r'        \includegraphics[width=\textwidth]{outputs/regression/bivariate/1hl/best/superimposed_train.png}',
r'        \caption{Train (1HL)}',
r'    \end{subfigure}',
r'    \begin{subfigure}[b]{0.32\textwidth}',
r'        \includegraphics[width=\textwidth]{outputs/regression/bivariate/1hl/best/superimposed_val.png}',
r'        \caption{Val (1HL)}',
r'    \end{subfigure}',
r'    \begin{subfigure}[b]{0.32\textwidth}',
r'        \includegraphics[width=\textwidth]{outputs/regression/bivariate/1hl/best/superimposed_test.png}',
r'        \caption{Test (1HL)}',
r'    \end{subfigure}',
r'    \caption{Bivariate regression (1HL$\times$16): 3D model output surface superimposed on target.}',
r'\end{figure}',
r'',
r'\subsubsection*{Scatter Plots: Target vs.\ Model Output}',
r'',
r'\begin{figure}[H]',
r'    \centering',
r'    \begin{subfigure}[b]{0.32\textwidth}',
r'        \includegraphics[width=\textwidth]{outputs/regression/bivariate/2hl/best/scatter_train.png}',
r'        \caption{Train (2HL)}',
r'    \end{subfigure}',
r'    \begin{subfigure}[b]{0.32\textwidth}',
r'        \includegraphics[width=\textwidth]{outputs/regression/bivariate/2hl/best/scatter_val.png}',
r'        \caption{Val (2HL)}',
r'    \end{subfigure}',
r'    \begin{subfigure}[b]{0.32\textwidth}',
r'        \includegraphics[width=\textwidth]{outputs/regression/bivariate/2hl/best/scatter_test.png}',
r'        \caption{Test (2HL)}',
r'    \end{subfigure}',
r'    \caption{Bivariate regression (2HL $16\times8$): scatter plots of target vs.\ model output.}',
r'\end{figure}',
r'',
r'\begin{figure}[H]',
r'    \centering',
r'    \begin{subfigure}[b]{0.32\textwidth}',
r'        \includegraphics[width=\textwidth]{outputs/regression/bivariate/1hl/best/scatter_train.png}',
r'        \caption{Train (1HL)}',
r'    \end{subfigure}',
r'    \begin{subfigure}[b]{0.32\textwidth}',
r'        \includegraphics[width=\textwidth]{outputs/regression/bivariate/1hl/best/scatter_val.png}',
r'        \caption{Val (1HL)}',
r'    \end{subfigure}',
r'    \begin{subfigure}[b]{0.32\textwidth}',
r'        \includegraphics[width=\textwidth]{outputs/regression/bivariate/1hl/best/scatter_test.png}',
r'        \caption{Test (1HL)}',
r'    \end{subfigure}',
r'    \caption{Bivariate regression (1HL$\times$16): scatter plots of target vs.\ model output.}',
r'\end{figure}',
r'',
r'\subsubsection*{Node Output Surfaces --- Best Architectures}',
r'',
r'\begin{figure}[H]',
r'    \centering',
r'    \begin{subfigure}[b]{0.32\textwidth}',
r'        \includegraphics[width=\textwidth]{outputs/regression/bivariate/2hl/best/train/surface_hidden_l1_n0.png}',
r'        \caption{H1-N0 (Train, 2HL)}',
r'    \end{subfigure}',
r'    \begin{subfigure}[b]{0.32\textwidth}',
r'        \includegraphics[width=\textwidth]{outputs/regression/bivariate/2hl/best/val/surface_hidden_l1_n0.png}',
r'        \caption{H1-N0 (Val, 2HL)}',
r'    \end{subfigure}',
r'    \begin{subfigure}[b]{0.32\textwidth}',
r'        \includegraphics[width=\textwidth]{outputs/regression/bivariate/2hl/best/test/surface_hidden_l1_n0.png}',
r'        \caption{H1-N0 (Test, 2HL)}',
r'    \end{subfigure}',
r'    \vspace{0.3cm}',
r'    \begin{subfigure}[b]{0.32\textwidth}',
r'        \includegraphics[width=\textwidth]{outputs/regression/bivariate/2hl/best/train/surface_hidden_l2_n0.png}',
r'        \caption{H2-N0 (Train, 2HL)}',
r'    \end{subfigure}',
r'    \begin{subfigure}[b]{0.32\textwidth}',
r'        \includegraphics[width=\textwidth]{outputs/regression/bivariate/2hl/best/val/surface_hidden_l2_n0.png}',
r'        \caption{H2-N0 (Val, 2HL)}',
r'    \end{subfigure}',
r'    \begin{subfigure}[b]{0.32\textwidth}',
r'        \includegraphics[width=\textwidth]{outputs/regression/bivariate/2hl/best/test/surface_hidden_l2_n0.png}',
r'        \caption{H2-N0 (Test, 2HL)}',
r'    \end{subfigure}',
r'    \vspace{0.3cm}',
r'    \begin{subfigure}[b]{0.32\textwidth}',
r'        \includegraphics[width=\textwidth]{outputs/regression/bivariate/2hl/best/train/surface_output_l3_n0.png}',
r'        \caption{Output (Train, 2HL)}',
r'    \end{subfigure}',
r'    \begin{subfigure}[b]{0.32\textwidth}',
r'        \includegraphics[width=\textwidth]{outputs/regression/bivariate/2hl/best/val/surface_output_l3_n0.png}',
r'        \caption{Output (Val, 2HL)}',
r'    \end{subfigure}',
r'    \begin{subfigure}[b]{0.32\textwidth}',
r'        \includegraphics[width=\textwidth]{outputs/regression/bivariate/2hl/best/test/surface_output_l3_n0.png}',
r'        \caption{Output (Test, 2HL)}',
r'    \end{subfigure}',
r'    \caption{Bivariate regression (2HL $16\times8$): H1-N0, H2-N0, and output node surfaces. Additional nodes in Appendix~\ref{app:biv2hl}.}',
r'\end{figure}',
r'',
r'\begin{figure}[H]',
r'    \centering',
r'    \begin{subfigure}[b]{0.32\textwidth}',
r'        \includegraphics[width=\textwidth]{outputs/regression/bivariate/1hl/best/train/surface_hidden_l1_n0.png}',
r'        \caption{H1-N0 (Train, 1HL)}',
r'    \end{subfigure}',
r'    \begin{subfigure}[b]{0.32\textwidth}',
r'        \includegraphics[width=\textwidth]{outputs/regression/bivariate/1hl/best/val/surface_hidden_l1_n0.png}',
r'        \caption{H1-N0 (Val, 1HL)}',
r'    \end{subfigure}',
r'    \begin{subfigure}[b]{0.32\textwidth}',
r'        \includegraphics[width=\textwidth]{outputs/regression/bivariate/1hl/best/test/surface_hidden_l1_n0.png}',
r'        \caption{H1-N0 (Test, 1HL)}',
r'    \end{subfigure}',
r'    \vspace{0.3cm}',
r'    \begin{subfigure}[b]{0.32\textwidth}',
r'        \includegraphics[width=\textwidth]{outputs/regression/bivariate/1hl/best/train/surface_output_l2_n0.png}',
r'        \caption{Output (Train, 1HL)}',
r'    \end{subfigure}',
r'    \begin{subfigure}[b]{0.32\textwidth}',
r'        \includegraphics[width=\textwidth]{outputs/regression/bivariate/1hl/best/val/surface_output_l2_n0.png}',
r'        \caption{Output (Val, 1HL)}',
r'    \end{subfigure}',
r'    \begin{subfigure}[b]{0.32\textwidth}',
r'        \includegraphics[width=\textwidth]{outputs/regression/bivariate/1hl/best/test/surface_output_l2_n0.png}',
r'        \caption{Output (Test, 1HL)}',
r'    \end{subfigure}',
r'    \caption{Bivariate regression (1HL$\times$16): H1-N0 and output node surfaces. Additional nodes in Appendix~\ref{app:biv1hl}.}',
r'\end{figure}',
r'',
r'\subsection{Comparison with Assignment 1: Regression}',
r'',
r'\begin{table}[H]',
r'\centering',
r'\caption{Regression: Assignment~1 (linear perceptron) vs.\ Assignment~2 (FCNN).}',
r'\begin{tabular}{lllrr}',
r'\toprule',
r'Dataset & Model & Architecture & Test RMSE & Test \%RMSE \\',
r'\midrule',
r'Dataset 1 (Univariate) & Single Neuron (A1) & Linear perceptron & 1.2662 & 53.52\% \\',
r'                        & FCNN (A2) & 1HL$\times$2 & 0.0738 & 3.198\% \\',
r'\midrule',
r'Dataset 2 (Bivariate)  & Single Neuron (A1) & Linear perceptron (2D) & 3.3342 & 83.64\% \\',
r'                        & FCNN (A2, 1HL) & 1HL$\times$16 & 0.0569 & 1.417\% \\',
r'                        & FCNN (A2, 2HL) & 2HL $16\times8$ & 0.0585 & 1.457\% \\',
r'\bottomrule',
r'\end{tabular}',
r'\end{table}',
r'',
r'The linear perceptron from A1 incurs 53.52\% and 83.64\% test \%RMSE on non-linear targets. The FCNN reduces test \%RMSE by over $16\times$ (univariate) and $57\times$ (bivariate) by composing sigmoid hidden activations.',
r'',
r'\subsection{Inferences on Regression Results}',
r'\begin{itemize}',
r'    \item Both error curves show a steep initial decrease followed by a stable plateau, indicating rapid convergence.',
r'    \item The model-output overlay plots confirm that the FCNNs accurately reproduce the underlying non-linear target functions.',
r'    \item Scatter plots show predictions closely clustered along the perfect-fit diagonal across all splits.',
r'    \item 1HL and 2HL achieve nearly identical test \%RMSE for the bivariate task ($\approx 1.4\%$), showing one well-sized hidden layer already captures the dominant non-linearity.',
r'    \item Larger architectures do not consistently outperform smaller ones under online SGD with fixed epochs.',
r'\end{itemize}',
r'',
r'%===========================================================================',
r'\section{Comparison and Inferences: Assignment 1 vs.\ Assignment 2}',
r'',
r'\begin{enumerate}',
r'    \item \textbf{Representational Failure Solved:} Single-layer perceptrons achieved 26.6\% on NLS (below chance) and RMSE reduced by $57\times$ on bivariate regression. FCNN hidden units construct localised non-linear basis functions that compose to form arbitrarily complex boundaries.',
r'    \item \textbf{Bottleneck Configurations:} 2HL architectures with $h_1>h_2$ compress internal representations, achieving equivalent or better generalisation with fewer parameters in the second layer.',
r'    \item \textbf{Softmax Output:} Produces a normalised probability distribution over classes, ensuring probabilities sum to 1 and providing well-calibrated class-specific confidence scores.',
r'    \item \textbf{SGD vs.\ Batch GD:} Online SGD ($\eta=0.5$) introduces stochasticity that can escape shallow local minima, critical for the NLS non-linear landscape. Batch GD (A1, $\eta=0.01$) produced smooth curves but failed on NLS.',
r'\end{enumerate}',
r'',
r'%===========================================================================',
r'\appendix',
r'',
r'\section{NLS Classification: Additional Hidden Node Surfaces}',
r'\label{app:nls}',
r'',
r'\begin{figure}[H]',
r'    \centering',
r'    \begin{subfigure}[b]{0.32\textwidth}',
r'        \includegraphics[width=\textwidth]{outputs/classification/nls/best/train/surface_hidden_l1_n1.png}',
r'        \caption{H1-N1 (Train)}',
r'    \end{subfigure}',
r'    \begin{subfigure}[b]{0.32\textwidth}',
r'        \includegraphics[width=\textwidth]{outputs/classification/nls/best/val/surface_hidden_l1_n1.png}',
r'        \caption{H1-N1 (Val)}',
r'    \end{subfigure}',
r'    \begin{subfigure}[b]{0.32\textwidth}',
r'        \includegraphics[width=\textwidth]{outputs/classification/nls/best/test/surface_hidden_l1_n1.png}',
r'        \caption{H1-N1 (Test)}',
r'    \end{subfigure}',
r'    \vspace{0.3cm}',
r'    \begin{subfigure}[b]{0.32\textwidth}',
r'        \includegraphics[width=\textwidth]{outputs/classification/nls/best/train/surface_hidden_l1_n2.png}',
r'        \caption{H1-N2 (Train)}',
r'    \end{subfigure}',
r'    \begin{subfigure}[b]{0.32\textwidth}',
r'        \includegraphics[width=\textwidth]{outputs/classification/nls/best/val/surface_hidden_l1_n2.png}',
r'        \caption{H1-N2 (Val)}',
r'    \end{subfigure}',
r'    \begin{subfigure}[b]{0.32\textwidth}',
r'        \includegraphics[width=\textwidth]{outputs/classification/nls/best/test/surface_hidden_l1_n2.png}',
r'        \caption{H1-N2 (Test)}',
r'    \end{subfigure}',
r'    \vspace{0.3cm}',
r'    \begin{subfigure}[b]{0.32\textwidth}',
r'        \includegraphics[width=\textwidth]{outputs/classification/nls/best/train/surface_hidden_l2_n1.png}',
r'        \caption{H2-N1 (Train)}',
r'    \end{subfigure}',
r'    \begin{subfigure}[b]{0.32\textwidth}',
r'        \includegraphics[width=\textwidth]{outputs/classification/nls/best/val/surface_hidden_l2_n1.png}',
r'        \caption{H2-N1 (Val)}',
r'    \end{subfigure}',
r'    \begin{subfigure}[b]{0.32\textwidth}',
r'        \includegraphics[width=\textwidth]{outputs/classification/nls/best/test/surface_hidden_l2_n1.png}',
r'        \caption{H2-N1 (Test)}',
r'    \end{subfigure}',
r'    \caption{NLS 2HL $16\times8$: additional hidden node surfaces (H1-N1, H1-N2, H2-N1). The complete set of 27 node surfaces per split is in the code output directory.}',
r'\end{figure}',
r'',
r'\section{Bivariate Regression (2HL): Additional Node Surfaces}',
r'\label{app:biv2hl}',
r'',
r'\begin{figure}[H]',
r'    \centering',
r'    \begin{subfigure}[b]{0.32\textwidth}',
r'        \includegraphics[width=\textwidth]{outputs/regression/bivariate/2hl/best/train/surface_hidden_l1_n1.png}',
r'        \caption{H1-N1 (Train)}',
r'    \end{subfigure}',
r'    \begin{subfigure}[b]{0.32\textwidth}',
r'        \includegraphics[width=\textwidth]{outputs/regression/bivariate/2hl/best/val/surface_hidden_l1_n1.png}',
r'        \caption{H1-N1 (Val)}',
r'    \end{subfigure}',
r'    \begin{subfigure}[b]{0.32\textwidth}',
r'        \includegraphics[width=\textwidth]{outputs/regression/bivariate/2hl/best/test/surface_hidden_l1_n1.png}',
r'        \caption{H1-N1 (Test)}',
r'    \end{subfigure}',
r'    \vspace{0.3cm}',
r'    \begin{subfigure}[b]{0.32\textwidth}',
r'        \includegraphics[width=\textwidth]{outputs/regression/bivariate/2hl/best/train/surface_hidden_l1_n2.png}',
r'        \caption{H1-N2 (Train)}',
r'    \end{subfigure}',
r'    \begin{subfigure}[b]{0.32\textwidth}',
r'        \includegraphics[width=\textwidth]{outputs/regression/bivariate/2hl/best/val/surface_hidden_l1_n2.png}',
r'        \caption{H1-N2 (Val)}',
r'    \end{subfigure}',
r'    \begin{subfigure}[b]{0.32\textwidth}',
r'        \includegraphics[width=\textwidth]{outputs/regression/bivariate/2hl/best/test/surface_hidden_l1_n2.png}',
r'        \caption{H1-N2 (Test)}',
r'    \end{subfigure}',
r'    \vspace{0.3cm}',
r'    \begin{subfigure}[b]{0.32\textwidth}',
r'        \includegraphics[width=\textwidth]{outputs/regression/bivariate/2hl/best/train/surface_hidden_l2_n1.png}',
r'        \caption{H2-N1 (Train)}',
r'    \end{subfigure}',
r'    \begin{subfigure}[b]{0.32\textwidth}',
r'        \includegraphics[width=\textwidth]{outputs/regression/bivariate/2hl/best/val/surface_hidden_l2_n1.png}',
r'        \caption{H2-N1 (Val)}',
r'    \end{subfigure}',
r'    \begin{subfigure}[b]{0.32\textwidth}',
r'        \includegraphics[width=\textwidth]{outputs/regression/bivariate/2hl/best/test/surface_hidden_l2_n1.png}',
r'        \caption{H2-N1 (Test)}',
r'    \end{subfigure}',
r'    \caption{Bivariate 2HL $16\times8$: additional node surfaces (H1-N1, H1-N2, H2-N1). Full node surface set available in the code output directory.}',
r'\end{figure}',
r'',
r'\section{Bivariate Regression (1HL): Additional Node Surfaces}',
r'\label{app:biv1hl}',
r'',
r'\begin{figure}[H]',
r'    \centering',
r'    \begin{subfigure}[b]{0.32\textwidth}',
r'        \includegraphics[width=\textwidth]{outputs/regression/bivariate/1hl/best/train/surface_hidden_l1_n1.png}',
r'        \caption{H1-N1 (Train)}',
r'    \end{subfigure}',
r'    \begin{subfigure}[b]{0.32\textwidth}',
r'        \includegraphics[width=\textwidth]{outputs/regression/bivariate/1hl/best/val/surface_hidden_l1_n1.png}',
r'        \caption{H1-N1 (Val)}',
r'    \end{subfigure}',
r'    \begin{subfigure}[b]{0.32\textwidth}',
r'        \includegraphics[width=\textwidth]{outputs/regression/bivariate/1hl/best/test/surface_hidden_l1_n1.png}',
r'        \caption{H1-N1 (Test)}',
r'    \end{subfigure}',
r'    \vspace{0.3cm}',
r'    \begin{subfigure}[b]{0.32\textwidth}',
r'        \includegraphics[width=\textwidth]{outputs/regression/bivariate/1hl/best/train/surface_hidden_l1_n2.png}',
r'        \caption{H1-N2 (Train)}',
r'    \end{subfigure}',
r'    \begin{subfigure}[b]{0.32\textwidth}',
r'        \includegraphics[width=\textwidth]{outputs/regression/bivariate/1hl/best/val/surface_hidden_l1_n2.png}',
r'        \caption{H1-N2 (Val)}',
r'    \end{subfigure}',
r'    \begin{subfigure}[b]{0.32\textwidth}',
r'        \includegraphics[width=\textwidth]{outputs/regression/bivariate/1hl/best/test/surface_hidden_l1_n2.png}',
r'        \caption{H1-N2 (Test)}',
r'    \end{subfigure}',
r'    \caption{Bivariate 1HL$\times$16: additional node surfaces (H1-N1, H1-N2). All 16 hidden node surfaces are available in the code output directory.}',
r'\end{figure}',
r'',
r'\end{document}',
)

with open('Group11_Assignment2_report_v9.tex', 'w', encoding='utf-8') as f:
    f.write('\n'.join(lines))

print(f"Written {len(lines)} lines to Group11_Assignment2_report_v9.tex")
